spring:
  datasource:
    # Add library 'Gradle: org.testcontainers' to classPath 설정 금지
    # 설정 시, 테스트 컨테이너 더미가 삭제되지 않고 남아있는 버그가 있음
    # submodule의 classPath에 등록하라는 것인데, mainmodule의 classPath에 등록되어 있으므로 정상 동작함
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8:///
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 1000
    open-in-view: false

jwt:
  token:
    secret-key: 7J206rKD7J2AIO2MqOyKpOybjOuTnCDsnoXri4jri6Qu
    access-token-expiresin: 1800000 # 30분
    refresh-token-expiresin: 604800000 # 7일


logging.level:
  org.hibernate.type: trace
