spring:
  devtools:
    livereload:
      enabled: true

  # datasource:
  #   url: ${DB_URL:jdbc:mysql://35.197.7.73:3306/ludo}
  #   username: ${DB_USERNAME:ludo-backend}
  #   password: ${DB_PASSWORD:ludodb777!}
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 34.127.77.94 # 로컬에서 테스트 할 때는 localhost 사용
      port: 6379
      password: ludoredis777!

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 1000

    open-in-view: false

oauth2:
  client:
    registration:
      naver:
        client-id: V9GiBd_m8pFGJFQqtAVL
        client-secret: ETIXZl1wLa
        # 기존 도메인
        #        login-redirect-uri: https://ludoapi.store/api/auth/login/naver/callback
        #        signup-redirect-uri: https://ludoapi.store/api/auth/signup/naver/callback
        # 신규 도메인
        login-redirect-uri: https://ludo.study/api/auth/login/naver/callback
        signup-redirect-uri: https://ludo.study/api/auth/signup/naver/callback
      kakao:
        client-id: ed54c5ca30a1f77a6a017194159af556
        client-secret: 0lortXKR3XPY1KUSsRnrWVMdyl0Csz9O
        # 기존 도메인
        #        login-redirect-uri: https://ludoapi.store/api/auth/login/kakao/callback
        #        signup-redirect-uri: https://ludoapi.store/api/auth/signup/kakao/callback
        # 신규 도메인
        login-redirect-uri: https://ludo.study/api/auth/login/kakao/callback
        signup-redirect-uri: https://ludo.study/api/auth/signup/kakao/callback
      google:
        client-id: 497023308362-v0ldm3v1i4rcent1mubpn82bhj7qslev.apps.googleusercontent.com
        client-secret: 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
        # 기존 도메인
        #        login-redirect-uri: https://ludoapi.store/api/auth/login/google/callback
        #        signup-redirect-uri: https://ludoapi.store/api/auth/signup/google/callback
        # 신규 도메인
        login-redirect-uri: https://ludo.study/api/auth/login/google/callback
        signup-redirect-uri: https://ludo.study/api/auth/signup/google/callback
    provider:
      naver:
        authorization-uri: https://nid.naver.com/oauth2.0/authorize
        token-uri: https://nid.naver.com/oauth2.0/token
        user-info-uri: https://openapi.naver.com/v1/nid/me
        authorization-grant-type: authorization_code
      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        authorization-grant-type: authorization_code
      google:
        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
        token-uri: https://oauth2.googleapis.com/token
        user-info-uri: https://www.googleapis.com/userinfo/v2/me
        authorization-grant-type: authorization_code

jwt:
  token:
    secret-key: 7J206rKD7J2AIO2MqOyKpOybjOuTnCDsnoXri4jri6Qu
    access-token-expiresin: 1800000 # 30분
    refresh-token-expiresin: 604800000 # 7일

client:
  scheme: https
  #  domain: ludoapi.store # 기존
  #  url: https://ludoapi.store # 기존
  domain: ludo.study # 신규
  url: https://ludo.study # 신규

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
    defaults:
      enabled: true
  endpoint:
    health:
      show-components: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port:
      9999

server:
  port: 80
  tomcat:
    mbeanregistry:
      enabled: true

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
