name: Build Spring Application and upload the artifact

inputs:
  env:
    required: true
  pat:
    required: true
  artifact-build-dir:
    required: true
  artifact-with-tag:
    required: true

runs:
  using: composite
  steps:
    - name: checkout code and submodules
      uses: ./.github/workflows/actions/setup
      with:
        pat: ${{ inputs.pat }}

    - name: build with gradle
      shell: bash
      run: ./gradlew build -x test -Dspring.profiles.action=${{ inputs.env }} -ParchiveName=${{ inputs.artifact-build-dir }}/${{ inputs.artifact-with-tag }}.jar

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.artifact-with-tag }}.jar"
        path: "${{ inputs.artifact-build-dir }}/${{ inputs.artifact-with-tag }}"
