on:
  push:
    branches:
      - main
env:
  ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
  FILENAME: a:1
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.x.outputs.env }}
    steps:
      - name: step1
        id: x
        run: |
          echo "ENV: ${{env.ENV}}"
          echo "ENV=xxx" >> $GITHUB_ENV
          echo "env=xox" >> $GITHUB_OUTPUT
      - name: step2
        run: |
          echo "job1.step1 env: ${{ env.ENV }}"
          echo "job1.step1 env: ${{ steps.x.outputs.env }}"
          echo "job1.step1 env: ${{ needs.job1.outputs.env }}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: step2-1
        run: |
          echo ${{ env.ENV }}
          echo "job1.step1 env: ${{ needs.job1.outputs.env }}"
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: |
          echo "file1" > txt
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILENAME }}
          path: .
  download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.FILENAME }}
          path: .
