on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.step1.outputs.env }}
    steps:
      - name: step1
        id: job1
        run: |
          echo "ENV=xxx" >> $GITHUB_ENV
          echo "env=xox" >> $GITHUB_OUTPUT
      - name: step2
        run: |
          echo "job1.step1 env: ${{ env.ENV }}"
          echo "job1.step1 env: ${{ steps.step1.outputs.env }}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: step2-1
        run: |
          echo ${{ env.ENV }}
          echo "job1.step1 env: ${{ needs.job1.outputs.env }}"
