on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "ENV=xxx" >> $GITHUB_ENV
      - name: step2
        run: echo ${{ env.ENV }}
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: step2-1
        run: echo ${{ env.ENV }}
